<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Techno-311" failures="0" tests="82" name="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" time="93.433" errors="26" timestamp="31 Jan 2023 07:46:23 GMT" skipped="0">
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_EkycDemo_Auth_With_name3_Valid_UIN_Smoke" time="1.338">
    <error message="Failed at output validation" type="io.mosip.admin.fw.util.AdminTestException">
      <![CDATA[io.mosip.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testscripts.DemoAuthSimplePostForAutoGenId.test(DemoAuthSimplePostForAutoGenId.java:161)
	at jdk.internal.reflect.GeneratedMethodAccessor212.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:177)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:124)
]]>
    </error>
  </testcase> <!-- auth_EkycDemo_Auth_With_name3_Valid_UIN_Smoke -->
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_EkycDemo_Auth_With_phone_uin_InValid" time="0.964">
    <error message="Failed at output validation" type="io.mosip.admin.fw.util.AdminTestException">
      <![CDATA[io.mosip.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testscripts.DemoAuthSimplePostForAutoGenId.test(DemoAuthSimplePostForAutoGenId.java:161)
	at jdk.internal.reflect.GeneratedMethodAccessor212.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:177)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:124)
]]>
    </error>
  </testcase> <!-- auth_EkycDemo_Auth_With_phone_uin_InValid -->
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_DemoAuth_same_Name4_Valid_uin_Smoke_Pos" time="0.996"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_DemoAuth_DOB_Valid_Smoke_UIN_Neg" time="1.229"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_EkycDemo_blank_individual_ID" time="0.987"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_EkycDemo_Auth_With_Valid_UIN_Smoke" time="1.081">
    <error message="Failed at output validation" type="io.mosip.admin.fw.util.AdminTestException">
      <![CDATA[io.mosip.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testscripts.DemoAuthSimplePostForAutoGenId.test(DemoAuthSimplePostForAutoGenId.java:161)
	at jdk.internal.reflect.GeneratedMethodAccessor212.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:177)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:124)
]]>
    </error>
  </testcase> <!-- auth_EkycDemo_Auth_With_Valid_UIN_Smoke -->
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_EkycDemo_Auth_With_name_Valid_UIN_Smoke" time="0.981">
    <error message="Failed at output validation" type="io.mosip.admin.fw.util.AdminTestException">
      <![CDATA[io.mosip.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testscripts.DemoAuthSimplePostForAutoGenId.test(DemoAuthSimplePostForAutoGenId.java:161)
	at jdk.internal.reflect.GeneratedMethodAccessor212.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:177)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:124)
]]>
    </error>
  </testcase> <!-- auth_EkycDemo_Auth_With_name_Valid_UIN_Smoke -->
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_DemoAuth_Email_InValid_Email_VID" time="1.232"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_DemoAuth_gender_Valid_Smoke_Pos_VID" time="1.106"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_DemoAuth_revoke_vid_Pos" time="1.210">
    <error message="Failed at output validation" type="io.mosip.admin.fw.util.AdminTestException">
      <![CDATA[io.mosip.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testscripts.DemoAuthSimplePostForAutoGenId.test(DemoAuthSimplePostForAutoGenId.java:161)
	at jdk.internal.reflect.GeneratedMethodAccessor212.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:177)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:124)
]]>
    </error>
  </testcase> <!-- auth_DemoAuth_revoke_vid_Pos -->
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_DemoAuth_InValid_gender_VID" time="1.390"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_DemoAuth_DOB_Missing_individualId" time="0.970"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_DemoAuth_PhoneNumber__with_Valid_TVID_Smoke_Pos" time="1.341"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_DemoAuth_DOB_Unlock_AllValid_UIN_Neg" time="1.099"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_DemoAuth_InValid_uin_name" time="1.097"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_EkycDemo_Auth_With_Email_Valid_VID_Smoke" time="1.485"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_DemoAuth_same_Name2_Valid_uin_Smoke_Pos" time="1.183"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_EkycDemo_Auth_With_age_uin_InValid" time="0.966">
    <error message="Failed at output validation" type="io.mosip.admin.fw.util.AdminTestException">
      <![CDATA[io.mosip.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testscripts.DemoAuthSimplePostForAutoGenId.test(DemoAuthSimplePostForAutoGenId.java:161)
	at jdk.internal.reflect.GeneratedMethodAccessor212.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:177)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:124)
]]>
    </error>
  </testcase> <!-- auth_EkycDemo_Auth_With_age_uin_InValid -->
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_EkycDemo_Auth_With_phone_Valid_UIN_Neg" time="1.046">
    <error message="Failed at output validation" type="io.mosip.admin.fw.util.AdminTestException">
      <![CDATA[io.mosip.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testscripts.DemoAuthSimplePostForAutoGenId.test(DemoAuthSimplePostForAutoGenId.java:161)
	at jdk.internal.reflect.GeneratedMethodAccessor212.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:177)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:124)
]]>
    </error>
  </testcase> <!-- auth_EkycDemo_Auth_With_phone_Valid_UIN_Neg -->
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_DemoAuth_Email_Valid_Smoke_Pos_VID" time="1.139"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_EkycDemo_Auth_With_email_Valid_UIN_Smoke" time="0.896">
    <error message="Failed at output validation" type="io.mosip.admin.fw.util.AdminTestException">
      <![CDATA[io.mosip.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testscripts.DemoAuthSimplePostForAutoGenId.test(DemoAuthSimplePostForAutoGenId.java:161)
	at jdk.internal.reflect.GeneratedMethodAccessor212.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:177)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:124)
]]>
    </error>
  </testcase> <!-- auth_EkycDemo_Auth_With_email_Valid_UIN_Smoke -->
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_EkycDemo_Auth_With_InValid_gender_With_VID" time="1.306"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_EkycDemo_missing_individual_ID" time="0.976"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_DemoAuth_DOB_Invalid_transactionId_uin_Pos" time="1.046"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_EkycDemo_Auth_With_revoke_VID" time="1.580">
    <error message="Failed at output validation" type="io.mosip.admin.fw.util.AdminTestException">
      <![CDATA[io.mosip.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testscripts.DemoAuthSimplePostForAutoGenId.test(DemoAuthSimplePostForAutoGenId.java:161)
	at jdk.internal.reflect.GeneratedMethodAccessor212.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:177)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:124)
]]>
    </error>
  </testcase> <!-- auth_EkycDemo_Auth_With_revoke_VID -->
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_DemoAuth_DOB_Valid_Smoke_VID_Pos" time="1.145"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_DemoAuth_same_Name5_Valid_uin_Smoke_Pos" time="0.981"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_DemoAuth_DOB_Blank_individualId" time="0.965"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_DemoAuth_same_Name6_Valid_uin_Smoke_Pos" time="1.043"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_EkycDemo_Auth_With_InValid_uin_email" time="0.985">
    <error message="Failed at output validation" type="io.mosip.admin.fw.util.AdminTestException">
      <![CDATA[io.mosip.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testscripts.DemoAuthSimplePostForAutoGenId.test(DemoAuthSimplePostForAutoGenId.java:161)
	at jdk.internal.reflect.GeneratedMethodAccessor212.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:177)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:124)
]]>
    </error>
  </testcase> <!-- auth_EkycDemo_Auth_With_InValid_uin_email -->
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_EkycDemo_Auth_With_Invalid_age_vid" time="0.989"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_EkycDemo_DOB_blank_transactionId_vid" time="1.721"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_DemoAuth_same_Name1_Valid_uin_Smoke_Pos" time="0.971"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_DemoAuth_dummy_partnerkey_uin_Pos" time="0.906">
    <error message="Failed at output validation" type="io.mosip.admin.fw.util.AdminTestException">
      <![CDATA[io.mosip.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testscripts.DemoAuthSimplePostForAutoGenId.test(DemoAuthSimplePostForAutoGenId.java:161)
	at jdk.internal.reflect.GeneratedMethodAccessor212.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:177)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:124)
]]>
    </error>
  </testcase> <!-- auth_DemoAuth_dummy_partnerkey_uin_Pos -->
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_EkycDemo_Auth_With_InValid_uin_DOB" time="1.045">
    <error message="Failed at output validation" type="io.mosip.admin.fw.util.AdminTestException">
      <![CDATA[io.mosip.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testscripts.DemoAuthSimplePostForAutoGenId.test(DemoAuthSimplePostForAutoGenId.java:161)
	at jdk.internal.reflect.GeneratedMethodAccessor212.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:177)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:124)
]]>
    </error>
  </testcase> <!-- auth_EkycDemo_Auth_With_InValid_uin_DOB -->
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_DemoAuth_Name_Valid_Smoke_VID_Pos" time="1.211"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_DemoAuth_Email_Valid_Smoke_Poss_VID" time="1.123"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_EkycDemo_Auth_With_name_Valid_VID_Smoke" time="1.471"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_DemoAuth_InValid_Name_VID" time="1.542"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_DemoAuth_age_InValid_uin" time="0.967">
    <error message="Failed at output validation" type="io.mosip.admin.fw.util.AdminTestException">
      <![CDATA[io.mosip.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testscripts.DemoAuthSimplePostForAutoGenId.test(DemoAuthSimplePostForAutoGenId.java:161)
	at jdk.internal.reflect.GeneratedMethodAccessor212.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:177)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:124)
]]>
    </error>
  </testcase> <!-- auth_DemoAuth_age_InValid_uin -->
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_EkycDemo_Auth_With_name6_Valid_UIN_Smoke" time="1.147">
    <error message="Failed at output validation" type="io.mosip.admin.fw.util.AdminTestException">
      <![CDATA[io.mosip.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testscripts.DemoAuthSimplePostForAutoGenId.test(DemoAuthSimplePostForAutoGenId.java:161)
	at jdk.internal.reflect.GeneratedMethodAccessor212.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:177)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:124)
]]>
    </error>
  </testcase> <!-- auth_EkycDemo_Auth_With_name6_Valid_UIN_Smoke -->
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_DemoAuth_same_Name3_Valid_uin_Smoke_Pos" time="0.954"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_EkycDemo_Auth_With_InValid_uin_name" time="0.961">
    <error message="Failed at output validation" type="io.mosip.admin.fw.util.AdminTestException">
      <![CDATA[io.mosip.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testscripts.DemoAuthSimplePostForAutoGenId.test(DemoAuthSimplePostForAutoGenId.java:161)
	at jdk.internal.reflect.GeneratedMethodAccessor212.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:177)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:124)
]]>
    </error>
  </testcase> <!-- auth_EkycDemo_Auth_With_InValid_uin_name -->
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_DemoAuth_Email_InValid_uin_Email" time="0.918"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_DemoAuth_PhoneNumber_InValid_PhoneNumber_VID" time="1.236"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_DemoAuth_DOB_Lock_Permanent_Valid_UIN_Neg" time="0.978"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_DemoAuth_age_Valid_Smoke_VID_Pos" time="1.161"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_EkycDemo_DOB_Invalid_transactionId_Pos_vid" time="1.597"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_EkycDemo_Auth_With_gender_Valid_UIN_Smoke" time="1.076">
    <error message="Failed at output validation" type="io.mosip.admin.fw.util.AdminTestException">
      <![CDATA[io.mosip.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testscripts.DemoAuthSimplePostForAutoGenId.test(DemoAuthSimplePostForAutoGenId.java:161)
	at jdk.internal.reflect.GeneratedMethodAccessor212.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:177)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:124)
]]>
    </error>
  </testcase> <!-- auth_EkycDemo_Auth_With_gender_Valid_UIN_Smoke -->
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_DemoAuth_age_Valid_uin_Smoke_Pos" time="1.023"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_DemoAuth_DOB_Blank_transactionId_uin_Pos" time="1.036"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_EkycDemo_Auth_With_InValid_name_With_VID" time="1.275"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_DemoAuth_DOB_InValid_uin_Dateofbirth" time="0.980"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_EkycDemo_Auth_With_name4_Valid_UIN_Smoke" time="1.029">
    <error message="Failed at output validation" type="io.mosip.admin.fw.util.AdminTestException">
      <![CDATA[io.mosip.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testscripts.DemoAuthSimplePostForAutoGenId.test(DemoAuthSimplePostForAutoGenId.java:161)
	at jdk.internal.reflect.GeneratedMethodAccessor212.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:177)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:124)
]]>
    </error>
  </testcase> <!-- auth_EkycDemo_Auth_With_name4_Valid_UIN_Smoke -->
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_EkycDemo_Auth_With_name5_Valid_UIN_Smoke" time="1.024">
    <error message="Failed at output validation" type="io.mosip.admin.fw.util.AdminTestException">
      <![CDATA[io.mosip.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testscripts.DemoAuthSimplePostForAutoGenId.test(DemoAuthSimplePostForAutoGenId.java:161)
	at jdk.internal.reflect.GeneratedMethodAccessor212.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:177)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:124)
]]>
    </error>
  </testcase> <!-- auth_EkycDemo_Auth_With_name5_Valid_UIN_Smoke -->
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_EkycDemo_Auth_With_InValid_uin_gender" time="0.952">
    <error message="Failed at output validation" type="io.mosip.admin.fw.util.AdminTestException">
      <![CDATA[io.mosip.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testscripts.DemoAuthSimplePostForAutoGenId.test(DemoAuthSimplePostForAutoGenId.java:161)
	at jdk.internal.reflect.GeneratedMethodAccessor212.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:177)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:124)
]]>
    </error>
  </testcase> <!-- auth_EkycDemo_Auth_With_InValid_uin_gender -->
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_EkycDemo_Auth_With_ImValid_partner_uin_Smoke" time="0.969">
    <error message="Failed at output validation" type="io.mosip.admin.fw.util.AdminTestException">
      <![CDATA[io.mosip.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testscripts.DemoAuthSimplePostForAutoGenId.test(DemoAuthSimplePostForAutoGenId.java:161)
	at jdk.internal.reflect.GeneratedMethodAccessor212.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:177)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:124)
]]>
    </error>
  </testcase> <!-- auth_EkycDemo_Auth_With_ImValid_partner_uin_Smoke -->
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_EkycDemo_Auth_With_Valid_VID_Smoke" time="1.489"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_DemoAuth_DOB_InValid_Dateofbirth_with_VID" time="1.238"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_EkycDemo_Auth_With_name2_Valid_UIN_Smoke" time="1.019">
    <error message="Failed at output validation" type="io.mosip.admin.fw.util.AdminTestException">
      <![CDATA[io.mosip.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testscripts.DemoAuthSimplePostForAutoGenId.test(DemoAuthSimplePostForAutoGenId.java:161)
	at jdk.internal.reflect.GeneratedMethodAccessor212.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:177)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:124)
]]>
    </error>
  </testcase> <!-- auth_EkycDemo_Auth_With_name2_Valid_UIN_Smoke -->
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_EkycDemo_Auth_With_age_Valid_UIN_Smoke" time="1.044">
    <error message="Failed at output validation" type="io.mosip.admin.fw.util.AdminTestException">
      <![CDATA[io.mosip.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testscripts.DemoAuthSimplePostForAutoGenId.test(DemoAuthSimplePostForAutoGenId.java:161)
	at jdk.internal.reflect.GeneratedMethodAccessor212.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:177)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:124)
]]>
    </error>
  </testcase> <!-- auth_EkycDemo_Auth_With_age_Valid_UIN_Smoke -->
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_EkycDemo_DOB_Unlock_Valid_Smoke_UIN_Neg" time="1.049">
    <error message="Failed at output validation" type="io.mosip.admin.fw.util.AdminTestException">
      <![CDATA[io.mosip.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testscripts.DemoAuthSimplePostForAutoGenId.test(DemoAuthSimplePostForAutoGenId.java:161)
	at jdk.internal.reflect.GeneratedMethodAccessor212.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:177)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:124)
]]>
    </error>
  </testcase> <!-- auth_EkycDemo_DOB_Unlock_Valid_Smoke_UIN_Neg -->
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_EkycDemo_Auth_With_gender_Valid_VID_Smoke" time="1.407"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_EkycDemo_Auth_With_age_Valid_VID_Smoke" time="1.642"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_DemoAuth_invalid_age_VID" time="1.073"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_DemoAuth_DOB_Lock_Permanent_AllValid_UIN_Neg" time="1.088"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_EkycDemo_without_individual_type_ID_Pos_vid" time="1.606"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_DemoAuth_DOB_Unlock_Valid_Smoke_UIN_Neg" time="0.988"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_EkycDemo_Auth_With_InValid_email_With_VID" time="1.286"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_DemoAuth_PhoneNumber_InValid_uin_PhoneNumber" time="1.020"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_EkycDemo_Auth_With_name7_Valid_UIN_Smoke" time="1.090">
    <error message="Failed at output validation" type="io.mosip.admin.fw.util.AdminTestException">
      <![CDATA[io.mosip.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testscripts.DemoAuthSimplePostForAutoGenId.test(DemoAuthSimplePostForAutoGenId.java:161)
	at jdk.internal.reflect.GeneratedMethodAccessor212.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:177)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:124)
]]>
    </error>
  </testcase> <!-- auth_EkycDemo_Auth_With_name7_Valid_UIN_Smoke -->
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_EkycDemo_Auth_With_Invalid_phone_vid" time="1.452"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_DemoAuth_PhoneNumber_Valid_VID_Smoke_Pos" time="1.186"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_EkycDemo_Auth_With_name1_Valid_UIN_Smoke" time="1.072">
    <error message="Failed at output validation" type="io.mosip.admin.fw.util.AdminTestException">
      <![CDATA[io.mosip.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testscripts.DemoAuthSimplePostForAutoGenId.test(DemoAuthSimplePostForAutoGenId.java:161)
	at jdk.internal.reflect.GeneratedMethodAccessor212.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:177)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:124)
]]>
    </error>
  </testcase> <!-- auth_EkycDemo_Auth_With_name1_Valid_UIN_Smoke -->
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_EkycDemo_DOB_Lock_Permanent_Valid_Smoke_UIN_Pos" time="1.048">
    <error message="Failed at output validation" type="io.mosip.admin.fw.util.AdminTestException">
      <![CDATA[io.mosip.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testscripts.DemoAuthSimplePostForAutoGenId.test(DemoAuthSimplePostForAutoGenId.java:161)
	at jdk.internal.reflect.GeneratedMethodAccessor212.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:177)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:124)
]]>
    </error>
  </testcase> <!-- auth_EkycDemo_DOB_Lock_Permanent_Valid_Smoke_UIN_Pos -->
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_DemoAuth_InValid_uin_gender" time="0.981"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_EkycDemo_Auth_With_phone_Valid_VID_Smoke" time="1.512"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_DemoAuth_gender_Valid_uin_Smoke_Pos" time="0.929"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_DemoAuth_Name_Valid_uin_Smoke_Pos" time="1.003"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_DemoAuth_DOB_InValid_individualId_VID" time="0.934"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_EkycDemo_Auth_With_InValid_DOB_With_VID" time="1.304"/>
  <testcase classname="io.mosip.testscripts.DemoAuthSimplePostForAutoGenId" name="auth_DemoAuth_same_Name7_Valid_uin_Smoke_Pos" time="0.948"/>
</testsuite> <!-- io.mosip.testscripts.DemoAuthSimplePostForAutoGenId -->
