<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Techno-311" failures="0" tests="68" name="io.mosip.testscripts.MultiFactorAuthNew" time="187.436" errors="12" timestamp="31 Jan 2023 07:46:23 GMT" skipped="0">
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_Face_With_Valid_uin_Smoke_Pos" time="2.408"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_Face_With_Valid_vid_Smoke_Pos" time="3.276"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_LeftIris_With_VID_With_Face_Invalid" time="3.023"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_LeftLittleFinger_With_Valid_VID_Smoke_Pos" time="3.356"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_LeftIndexFingerr_With_Valid_vid_Smoke_Pos" time="3.871"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_LeftMiddleFingerr_With_uin_InValid_transactionId_Pos" time="2.447"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_LeftIris_With_VID_invalid_Bio-Type_value_as_IR_instead_of_Iris" time="2.359"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_LeftIris_With_VID_valid_bioType_and_invalid_digitalId_type" time="2.568"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_LeftMiddleFingerr_With_uin_Valid_Smoke_Pos" time="2.514"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_RingFinger_With_vid_blank_transactionId_Pos" time="3.141"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_LeftIris_With_VID_INvalid_bioValue" time="3.200"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_with_uin_invalid_partner" time="2.137">
    <error message="Failed at output validation" type="io.mosip.admin.fw.util.AdminTestException">
      <![CDATA[io.mosip.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testscripts.MultiFactorAuthNew.test(MultiFactorAuthNew.java:184)
	at jdk.internal.reflect.GeneratedMethodAccessor210.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:177)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:124)
]]>
    </error>
  </testcase> <!-- auth_MultiFactorAuth_with_uin_invalid_partner -->
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_LeftIris_With_UIN_INvalid_bioValue" time="2.480"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_LeftIris_With_VID_missing_bioSubType" time="2.521"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_RightLittleFinger_With_uin_Valid_Smoke_Pos" time="2.664"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_RingFinger_With_missing_transactionId_uin_Pos" time="2.416"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_RingFinger_With_Valid_uin_Smoke_Pos" time="2.592"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_LeftIris_With_VID_InValid_transactionId_Pos" time="2.996"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_LeftMiddleFingerr_With_uin_blank_transactionId_Pos" time="2.451"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_LeftIris_With_UIN_With_Face_Invalid" time="2.117"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_LeftThumb_With_Valid_VID_Smoke_Pos" time="3.089"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_With_VID_invalid_Bio-Type_value_as_FIR_instead_of_Finger" time="2.510"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_Face_With_InValid_vid_transactionId_Pos" time="3.259"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_RightMiddleFinger_With_Valid_VID_Smoke_Pos" time="3.129"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_LeftIris_With_VID_blank_transactionId_Pos" time="3.184"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_LeftIris_With_VID_BLANK_bioType" time="1.724"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_LeftThumb_With_uin_Valid_Smoke_Pos" time="2.410"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_LeftIris_With_UIN_blank_bioSubType" time="2.332">
    <error message="Failed at output validation" type="io.mosip.admin.fw.util.AdminTestException">
      <![CDATA[io.mosip.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testscripts.MultiFactorAuthNew.test(MultiFactorAuthNew.java:184)
	at jdk.internal.reflect.GeneratedMethodAccessor210.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:177)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:124)
]]>
    </error>
  </testcase> <!-- auth_MultiFactorAuth_Biometric_LeftIris_With_UIN_blank_bioSubType -->
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_Face_With_revoked_vid" time="3.520">
    <error message="Failed at output validation" type="io.mosip.admin.fw.util.AdminTestException">
      <![CDATA[io.mosip.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testscripts.MultiFactorAuthNew.test(MultiFactorAuthNew.java:184)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:177)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:124)
]]>
    </error>
  </testcase> <!-- auth_MultiFactorAuth_Biometric_Face_With_revoked_vid -->
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_LeftIris_With_UIN_invalid_bioSubType" time="2.589">
    <error message="Failed at output validation" type="io.mosip.admin.fw.util.AdminTestException">
      <![CDATA[io.mosip.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testscripts.MultiFactorAuthNew.test(MultiFactorAuthNew.java:184)
	at jdk.internal.reflect.GeneratedMethodAccessor210.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:177)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:124)
]]>
    </error>
  </testcase> <!-- auth_MultiFactorAuth_Biometric_LeftIris_With_UIN_invalid_bioSubType -->
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_Face_With_Missing_transactionId_uin_Pos" time="2.294"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_LeftIris_With__VID_Valid_Smoke_Pos" time="3.113"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_LeftIris_With_UIN_invalid_Bio-Type_value_as_IR_instead_of_Iris" time="2.295">
    <error message="Failed at output validation" type="io.mosip.admin.fw.util.AdminTestException">
      <![CDATA[io.mosip.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testscripts.MultiFactorAuthNew.test(MultiFactorAuthNew.java:184)
	at jdk.internal.reflect.GeneratedMethodAccessor210.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:177)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:124)
]]>
    </error>
  </testcase> <!-- auth_MultiFactorAuth_Biometric_LeftIris_With_UIN_invalid_Bio-Type_value_as_IR_instead_of_Iris -->
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_LeftIris_With_VID_invalid_bioType" time="2.483"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_RingFinger_With_Valid_VID_Smoke_Pos" time="3.288"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_LeftIris_With_UIN_valid_bioType_and_invalid_digitalId_type" time="2.258">
    <error message="Failed at output validation" type="io.mosip.admin.fw.util.AdminTestException">
      <![CDATA[io.mosip.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testscripts.MultiFactorAuthNew.test(MultiFactorAuthNew.java:184)
	at jdk.internal.reflect.GeneratedMethodAccessor210.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:177)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:124)
]]>
    </error>
  </testcase> <!-- auth_MultiFactorAuth_Biometric_LeftIris_With_UIN_valid_bioType_and_invalid_digitalId_type -->
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_RightIndexFinger_With_Valid_VID_Smoke_Pos" time="3.719"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_LeftIris_With_UIN_missing_bioSubType" time="2.248">
    <error message="Failed at output validation" type="io.mosip.admin.fw.util.AdminTestException">
      <![CDATA[io.mosip.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testscripts.MultiFactorAuthNew.test(MultiFactorAuthNew.java:184)
	at jdk.internal.reflect.GeneratedMethodAccessor210.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:177)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:124)
]]>
    </error>
  </testcase> <!-- auth_MultiFactorAuth_Biometric_LeftIris_With_UIN_missing_bioSubType -->
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_With_UIN_invalid_Bio-Type_value_as_FIR_instead_of_Finger" time="2.261">
    <error message="Failed at output validation" type="io.mosip.admin.fw.util.AdminTestException">
      <![CDATA[io.mosip.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testscripts.MultiFactorAuthNew.test(MultiFactorAuthNew.java:184)
	at jdk.internal.reflect.GeneratedMethodAccessor210.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:177)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:124)
]]>
    </error>
  </testcase> <!-- auth_MultiFactorAuth_Biometric_With_UIN_invalid_Bio-Type_value_as_FIR_instead_of_Finger -->
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_Face_With_InValid_transactionId_uin_Pos" time="2.264"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_RightThumb_With_Valid_uin_Smoke_Pos" time="2.383"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_LeftIris_With_UIN_missing_bioType" time="2.326">
    <error message="Failed at output validation" type="io.mosip.admin.fw.util.AdminTestException">
      <![CDATA[io.mosip.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testscripts.MultiFactorAuthNew.test(MultiFactorAuthNew.java:184)
	at jdk.internal.reflect.GeneratedMethodAccessor210.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:177)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:124)
]]>
    </error>
  </testcase> <!-- auth_MultiFactorAuth_Biometric_LeftIris_With_UIN_missing_bioType -->
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_LeftIris_With_UIN_With_Finger_Invalid" time="2.110"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_RightIris_With_Valid_VID_Smoke_Pos" time="3.073">
    <error message="Failed at output validation" type="io.mosip.admin.fw.util.AdminTestException">
      <![CDATA[io.mosip.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testscripts.MultiFactorAuthNew.test(MultiFactorAuthNew.java:184)
	at jdk.internal.reflect.GeneratedMethodAccessor210.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:177)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:124)
]]>
    </error>
  </testcase> <!-- auth_MultiFactorAuth_Biometric_RightIris_With_Valid_VID_Smoke_Pos -->
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_RightLittleFinger_With_Valid_VID_Smoke_Pos" time="3.222"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_LeftIris_With_VID_blank_bioSubType" time="2.497"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_LeftIris_With_VID_With_Finger_Invalid" time="3.352"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_RightRingFinger_With_Valid_VID_Smoke_Pos" time="3.553"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_LeftIris_With_uin_Valid_Smoke_Pos" time="2.313"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_Face_With_blank_vid_transactionId_Pos" time="3.087"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_LeftLittleFinger_With_uin_Valid_Smoke_Pos" time="3.305"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_RightMiddleFinger_With_uin_Valid_Smoke_Pos" time="3.213"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_RightThumb_With_Valid_VID_Smoke_Pos" time="3.027"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_LeftIndexFingerr_With_uin_Valid_Smoke_Pos" time="2.708"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_RingFinger_With_invalid_transactionId_uin_Pos" time="2.526"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_LeftIris_With_UIN_BLANK_bioType" time="2.817">
    <error message="Failed at output validation" type="io.mosip.admin.fw.util.AdminTestException">
      <![CDATA[io.mosip.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testscripts.MultiFactorAuthNew.test(MultiFactorAuthNew.java:184)
	at jdk.internal.reflect.GeneratedMethodAccessor210.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:177)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:124)
]]>
    </error>
  </testcase> <!-- auth_MultiFactorAuth_Biometric_LeftIris_With_UIN_BLANK_bioType -->
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_LeftIris_With_VID_missing_bioType" time="2.541"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_RightIris_With_uin_Valid_Smoke_Pos" time="2.620"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_RingFinger_With_vid_InValid_transactionId" time="2.891"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_RightIndexFinger_With_uin_Valid_Smoke_Pos" time="3.487"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_RightRingFinger_With_uin_Valid_Smoke_Pos" time="2.637"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_LeftIris_With_uin_blank_transactionId_Pos" time="2.297"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_LeftIris_With_VID_blank_individualIdType_Pos" time="3.088"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_LeftMiddleFingerr_With_Valid_VID_Smoke_Pos" time="3.601"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_LeftIris_With_VID_invalid_bioSubType" time="2.607"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_LeftIris_With_UIN_InValid_transactionId_Pos" time="2.270"/>
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_LeftIris_With_UIN_invalid_bioType" time="2.174">
    <error message="Failed at output validation" type="io.mosip.admin.fw.util.AdminTestException">
      <![CDATA[io.mosip.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testscripts.MultiFactorAuthNew.test(MultiFactorAuthNew.java:184)
	at jdk.internal.reflect.GeneratedMethodAccessor210.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:177)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:124)
]]>
    </error>
  </testcase> <!-- auth_MultiFactorAuth_Biometric_LeftIris_With_UIN_invalid_bioType -->
  <testcase classname="io.mosip.testscripts.MultiFactorAuthNew" name="auth_MultiFactorAuth_Biometric_LeftIris_With_VID_invalid_individualIdType_Pos" time="3.205"/>
</testsuite> <!-- io.mosip.testscripts.MultiFactorAuthNew -->
