<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Techno-311" failures="0" tests="38" name="io.mosip.testrig.apirig.testscripts.KycAuth" time="58.948" errors="10" timestamp="01 Aug 2023 16:54:17 GMT" skipped="0">
  <testcase classname="io.mosip.testrig.apirig.testscripts.KycAuth" name="Esignet_KycBioAuth_vid_LeftIris_all_Valid_Smoke" time="1.998">
    <error message="Failed at output validation" type="io.mosip.testrig.apirig.admin.fw.util.AdminTestException">
      <![CDATA[io.mosip.testrig.apirig.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testrig.apirig.testscripts.KycAuth.test(KycAuth.java:133)
	at jdk.internal.reflect.GeneratedMethodAccessor212.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:160)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.main(MosipTestRunner.java:111)
]]>
    </error>
  </testcase> <!-- Esignet_KycBioAuth_vid_LeftIris_all_Valid_Smoke -->
  <testcase classname="io.mosip.testrig.apirig.testscripts.KycAuth" name="Esignet_KycDemoAuth_vid_all_Valid_Smoke" time="1.286">
    <error message="Failed at output validation" type="io.mosip.testrig.apirig.admin.fw.util.AdminTestException">
      <![CDATA[io.mosip.testrig.apirig.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testrig.apirig.testscripts.KycAuth.test(KycAuth.java:133)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:160)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.main(MosipTestRunner.java:111)
]]>
    </error>
  </testcase> <!-- Esignet_KycDemoAuth_vid_all_Valid_Smoke -->
  <testcase classname="io.mosip.testrig.apirig.testscripts.KycAuth" name="Esignet_KycDemoAuth_uin_Invalid_Data_Neg" time="1.266"/>
  <testcase classname="io.mosip.testrig.apirig.testscripts.KycAuth" name="Esignet_KycDemoAuth_vid_Phone_Invalid_Data_Neg" time="1.218"/>
  <testcase classname="io.mosip.testrig.apirig.testscripts.KycAuth" name="Esignet_KycBioAuth_uin_LeftIris_all_Valid_Smoke" time="1.998">
    <error message="Failed at output validation" type="io.mosip.testrig.apirig.admin.fw.util.AdminTestException">
      <![CDATA[io.mosip.testrig.apirig.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testrig.apirig.testscripts.KycAuth.test(KycAuth.java:133)
	at jdk.internal.reflect.GeneratedMethodAccessor212.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:160)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.main(MosipTestRunner.java:111)
]]>
    </error>
  </testcase> <!-- Esignet_KycBioAuth_uin_LeftIris_all_Valid_Smoke -->
  <testcase classname="io.mosip.testrig.apirig.testscripts.KycAuth" name="Esignet_KycDemoAuth_vid_Phone_all_Valid_Smoke" time="1.363">
    <error message="Failed at output validation" type="io.mosip.testrig.apirig.admin.fw.util.AdminTestException">
      <![CDATA[io.mosip.testrig.apirig.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testrig.apirig.testscripts.KycAuth.test(KycAuth.java:133)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:160)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.main(MosipTestRunner.java:111)
]]>
    </error>
  </testcase> <!-- Esignet_KycDemoAuth_vid_Phone_all_Valid_Smoke -->
  <testcase classname="io.mosip.testrig.apirig.testscripts.KycAuth" name="Esignet_KycBioAuth_uin_LeftIris_Invalid_Biovalue_Neg" time="1.418"/>
  <testcase classname="io.mosip.testrig.apirig.testscripts.KycAuth" name="Esignet_KycBioAuth_uin_all_Valid_Smoke" time="3.163">
    <error message="Failed at output validation" type="io.mosip.testrig.apirig.admin.fw.util.AdminTestException">
      <![CDATA[io.mosip.testrig.apirig.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testrig.apirig.testscripts.KycAuth.test(KycAuth.java:133)
	at jdk.internal.reflect.GeneratedMethodAccessor212.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:160)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.main(MosipTestRunner.java:111)
]]>
    </error>
  </testcase> <!-- Esignet_KycBioAuth_uin_all_Valid_Smoke -->
  <testcase classname="io.mosip.testrig.apirig.testscripts.KycAuth" name="Esignet_KycDemoAuth_uin_False_Invalid_Neg" time="1.287"/>
  <testcase classname="io.mosip.testrig.apirig.testscripts.KycAuth" name="Esignet_KycDemoAuth_uin_Null_PartnerId_Neg" time="1.211"/>
  <testcase classname="io.mosip.testrig.apirig.testscripts.KycAuth" name="Esignet_KycBioAuth_vid_all_Valid_Smoke" time="3.477">
    <error message="Failed at output validation" type="io.mosip.testrig.apirig.admin.fw.util.AdminTestException">
      <![CDATA[io.mosip.testrig.apirig.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testrig.apirig.testscripts.KycAuth.test(KycAuth.java:133)
	at jdk.internal.reflect.GeneratedMethodAccessor212.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:160)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.main(MosipTestRunner.java:111)
]]>
    </error>
  </testcase> <!-- Esignet_KycBioAuth_vid_all_Valid_Smoke -->
  <testcase classname="io.mosip.testrig.apirig.testscripts.KycAuth" name="Esignet_KycBioAuth_vid_RingFinger_all_Valid_Smoke" time="2.004">
    <error message="Failed at output validation" type="io.mosip.testrig.apirig.admin.fw.util.AdminTestException">
      <![CDATA[io.mosip.testrig.apirig.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testrig.apirig.testscripts.KycAuth.test(KycAuth.java:133)
	at jdk.internal.reflect.GeneratedMethodAccessor212.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:160)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.main(MosipTestRunner.java:111)
]]>
    </error>
  </testcase> <!-- Esignet_KycBioAuth_vid_RingFinger_all_Valid_Smoke -->
  <testcase classname="io.mosip.testrig.apirig.testscripts.KycAuth" name="Esignet_KycDemoAuth_uin_Null_MispLk_Neg" time="1.386"/>
  <testcase classname="io.mosip.testrig.apirig.testscripts.KycAuth" name="Esignet_KycDemoAuth_uin_Null_ClientId_Neg" time="1.322"/>
  <testcase classname="io.mosip.testrig.apirig.testscripts.KycAuth" name="Esignet_KycDemoAuth_uin_all_Valid_Smoke" time="1.780">
    <error message="Failed at output validation" type="io.mosip.testrig.apirig.admin.fw.util.AdminTestException">
      <![CDATA[io.mosip.testrig.apirig.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testrig.apirig.testscripts.KycAuth.test(KycAuth.java:133)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:160)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.main(MosipTestRunner.java:111)
]]>
    </error>
  </testcase> <!-- Esignet_KycDemoAuth_uin_all_Valid_Smoke -->
  <testcase classname="io.mosip.testrig.apirig.testscripts.KycAuth" name="Esignet_KycDemoAuth_uin_Invalid_PartnerId_Neg" time="1.203"/>
  <testcase classname="io.mosip.testrig.apirig.testscripts.KycAuth" name="Esignet_KycBioAuth_vid_Invalid_Biovalue_Neg" time="1.538"/>
  <testcase classname="io.mosip.testrig.apirig.testscripts.KycAuth" name="Esignet_KycDemoAuth_vid_Null_MispLk_Neg" time="1.251"/>
  <testcase classname="io.mosip.testrig.apirig.testscripts.KycAuth" name="Esignet_KycDemoAuth_vid_Null_ClientId_Neg" time="1.591"/>
  <testcase classname="io.mosip.testrig.apirig.testscripts.KycAuth" name="Esignet_KycDemoAuth_vid_Invalid_Data_Neg" time="1.196"/>
  <testcase classname="io.mosip.testrig.apirig.testscripts.KycAuth" name="Esignet_KycDemoAuth_uin_Invalid_MispLk_Neg" time="1.417"/>
  <testcase classname="io.mosip.testrig.apirig.testscripts.KycAuth" name="Esignet_KycBioAuth_vid_RingFinger_Invalid_Biovalue_Neg" time="1.422"/>
  <testcase classname="io.mosip.testrig.apirig.testscripts.KycAuth" name="Esignet_KycDemoAuth_vid_Invalid_ClientId_Neg" time="1.176"/>
  <testcase classname="io.mosip.testrig.apirig.testscripts.KycAuth" name="Esignet_KycBioAuth_uin_Invalid_Biovalue_Neg" time="2.015"/>
  <testcase classname="io.mosip.testrig.apirig.testscripts.KycAuth" name="Esignet_KycBioAuth_uin_RingFinger_Invalid_Biovalue_Neg" time="1.656"/>
  <testcase classname="io.mosip.testrig.apirig.testscripts.KycAuth" name="Esignet_KycDemoAuth_uin_Phone_False_Invalid_Neg" time="1.118"/>
  <testcase classname="io.mosip.testrig.apirig.testscripts.KycAuth" name="Esignet_KycDemoAuth_vid_Invalid_PartnerId_Neg" time="1.458"/>
  <testcase classname="io.mosip.testrig.apirig.testscripts.KycAuth" name="Esignet_KycDemoAuth_Vid_Phone_False_Invalid_Neg" time="1.246"/>
  <testcase classname="io.mosip.testrig.apirig.testscripts.KycAuth" name="Esignet_KycDemoAuth_Vid_False_Invalid_Neg" time="1.161"/>
  <testcase classname="io.mosip.testrig.apirig.testscripts.KycAuth" name="Esignet_KycDemoAuth_uin_Invalid_PartnerName_Neg" time="1.561"/>
  <testcase classname="io.mosip.testrig.apirig.testscripts.KycAuth" name="Esignet_KycDemoAuth_uin_Phone_all_Valid_Smoke" time="1.223">
    <error message="Failed at output validation" type="io.mosip.testrig.apirig.admin.fw.util.AdminTestException">
      <![CDATA[io.mosip.testrig.apirig.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testrig.apirig.testscripts.KycAuth.test(KycAuth.java:133)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:160)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.main(MosipTestRunner.java:111)
]]>
    </error>
  </testcase> <!-- Esignet_KycDemoAuth_uin_Phone_all_Valid_Smoke -->
  <testcase classname="io.mosip.testrig.apirig.testscripts.KycAuth" name="Esignet_KycDemoAuth_vid_Invalid_MispLk_Neg" time="1.212"/>
  <testcase classname="io.mosip.testrig.apirig.testscripts.KycAuth" name="Esignet_KycDemoAuth_uin_Invalid_ClientId_Neg" time="1.170"/>
  <testcase classname="io.mosip.testrig.apirig.testscripts.KycAuth" name="Esignet_KycDemoAuth_vid_Null_PartnerId_Neg" time="1.234"/>
  <testcase classname="io.mosip.testrig.apirig.testscripts.KycAuth" name="Esignet_KycBioAuth_uin_RingFinger_all_Valid_Smoke" time="2.049">
    <error message="Failed at output validation" type="io.mosip.testrig.apirig.admin.fw.util.AdminTestException">
      <![CDATA[io.mosip.testrig.apirig.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testrig.apirig.testscripts.KycAuth.test(KycAuth.java:133)
	at jdk.internal.reflect.GeneratedMethodAccessor212.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:160)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.main(MosipTestRunner.java:111)
]]>
    </error>
  </testcase> <!-- Esignet_KycBioAuth_uin_RingFinger_all_Valid_Smoke -->
  <testcase classname="io.mosip.testrig.apirig.testscripts.KycAuth" name="Esignet_KycBioAuth_vid_LeftIris_Invalid_Biovalue_Neg" time="1.922"/>
  <testcase classname="io.mosip.testrig.apirig.testscripts.KycAuth" name="Esignet_KycDemoAuth_uin_Phone_Invalid_Data_Neg" time="1.278"/>
  <testcase classname="io.mosip.testrig.apirig.testscripts.KycAuth" name="Esignet_KycDemoAuth_vid_Invalid_PartnerName_Neg" time="1.674"/>
</testsuite> <!-- io.mosip.testrig.apirig.testscripts.KycAuth -->
