<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Techno-311" failures="2" tests="4" name="AuthUnLock" time="15.892" errors="0" timestamp="16 Nov 2022 08:49:37 GMT">
  <testcase classname="io.mosip.testscripts.PostWithBodyWithOtpGenerate" name="" time="3.504"/>
  <testcase classname="io.mosip.testscripts.PostWithBodyWithOtpGenerate" name="Mimoto_AuthUnLock_Valid_UIN_All" time="5.124"/>
  <testcase classname="io.mosip.testscripts.PostWithBodyWithOtpGenerate" name="Mimoto_AuthUnLock_Valid_UIN_With_VID_All" time="3.388">
    <failure type="io.mosip.admin.fw.util.AdminTestException" message="Failed at output validation">
      <![CDATA[io.mosip.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testscripts.PostWithBodyWithOtpGenerate.test(PostWithBodyWithOtpGenerate.java:117)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:164)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:111)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- Mimoto_AuthUnLock_Valid_UIN_With_VID_All -->
  <testcase classname="io.mosip.testscripts.PostWithBodyWithOtpGenerate" name="Mimoto_AuthUnLock_With_InValid_OTP_All" time="3.865">
    <failure type="io.mosip.admin.fw.util.AdminTestException" message="Failed at output validation">
      <![CDATA[io.mosip.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testscripts.PostWithBodyWithOtpGenerate.test(PostWithBodyWithOtpGenerate.java:117)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:164)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:111)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- Mimoto_AuthUnLock_With_InValid_OTP_All -->
</testsuite> <!-- AuthUnLock -->
