<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Techno-311" failures="18" tests="29" name="EkycOtp" time="24.358" errors="0" timestamp="17 Nov 2023 04:11:36 GMT">
  <testcase classname="io.mosip.testrig.apirig.testscripts.OtpAuthNew" name="" time="1.508">
    <failure type="io.mosip.testrig.apirig.admin.fw.util.AdminTestException" message="Internal Server Error. Hence marking the test case as failed">
      <![CDATA[io.mosip.testrig.apirig.admin.fw.util.AdminTestException: Internal Server Error. Hence marking the test case as failed
	at io.mosip.testrig.apirig.authentication.fw.util.OutputValidationUtil.doJsonOutputValidation(OutputValidationUtil.java:476)
	at io.mosip.testrig.apirig.authentication.fw.util.OutputValidationUtil.doJsonOutputValidation(OutputValidationUtil.java:468)
	at io.mosip.testrig.apirig.testscripts.OtpAuthNew.test(OtpAuthNew.java:222)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:196)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.main(MosipTestRunner.java:137)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!--  -->
  <testcase classname="io.mosip.testrig.apirig.testscripts.OtpAuthNew" name="auth_EkycOtp_Auth_With_Valid_UIN_Smoke" time="1.402">
    <failure type="io.mosip.testrig.apirig.admin.fw.util.AdminTestException" message="Internal Server Error. Hence marking the test case as failed">
      <![CDATA[io.mosip.testrig.apirig.admin.fw.util.AdminTestException: Internal Server Error. Hence marking the test case as failed
	at io.mosip.testrig.apirig.authentication.fw.util.OutputValidationUtil.doJsonOutputValidation(OutputValidationUtil.java:476)
	at io.mosip.testrig.apirig.authentication.fw.util.OutputValidationUtil.doJsonOutputValidation(OutputValidationUtil.java:468)
	at io.mosip.testrig.apirig.testscripts.OtpAuthNew.test(OtpAuthNew.java:222)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:196)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.main(MosipTestRunner.java:137)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- auth_EkycOtp_Auth_With_Valid_UIN_Smoke -->
  <testcase classname="io.mosip.testrig.apirig.testscripts.OtpAuthNew" name="auth_EkycOtp_Auth_With_Valid__with_edited_updated_UIN_Smoke" time="1.291">
    <failure type="io.mosip.testrig.apirig.admin.fw.util.AdminTestException" message="Internal Server Error. Hence marking the test case as failed">
      <![CDATA[io.mosip.testrig.apirig.admin.fw.util.AdminTestException: Internal Server Error. Hence marking the test case as failed
	at io.mosip.testrig.apirig.authentication.fw.util.OutputValidationUtil.doJsonOutputValidation(OutputValidationUtil.java:476)
	at io.mosip.testrig.apirig.authentication.fw.util.OutputValidationUtil.doJsonOutputValidation(OutputValidationUtil.java:468)
	at io.mosip.testrig.apirig.testscripts.OtpAuthNew.test(OtpAuthNew.java:222)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:196)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.main(MosipTestRunner.java:137)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- auth_EkycOtp_Auth_With_Valid__with_edited_updated_UIN_Smoke -->
  <testcase classname="io.mosip.testrig.apirig.testscripts.OtpAuthNew" name="auth_EkycOtp_Auth_With_Infant_Valid_UIN_Smoke" time="1.354">
    <failure type="io.mosip.testrig.apirig.admin.fw.util.AdminTestException" message="Internal Server Error. Hence marking the test case as failed">
      <![CDATA[io.mosip.testrig.apirig.admin.fw.util.AdminTestException: Internal Server Error. Hence marking the test case as failed
	at io.mosip.testrig.apirig.authentication.fw.util.OutputValidationUtil.doJsonOutputValidation(OutputValidationUtil.java:476)
	at io.mosip.testrig.apirig.authentication.fw.util.OutputValidationUtil.doJsonOutputValidation(OutputValidationUtil.java:468)
	at io.mosip.testrig.apirig.testscripts.OtpAuthNew.test(OtpAuthNew.java:222)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:196)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.main(MosipTestRunner.java:137)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- auth_EkycOtp_Auth_With_Infant_Valid_UIN_Smoke -->
  <testcase classname="io.mosip.testrig.apirig.testscripts.OtpAuthNew" name="auth_EkycOtp_Auth_With_deactivate_UIN_Smoke" time="1.141">
    <skipped/>
  </testcase> <!-- auth_EkycOtp_Auth_With_deactivate_UIN_Smoke -->
  <testcase classname="io.mosip.testrig.apirig.testscripts.OtpAuthNew" name="auth_EkycOtp_Auth_With_draft_UIN_Smoke" time="0.001">
    <skipped/>
  </testcase> <!-- auth_EkycOtp_Auth_With_draft_UIN_Smoke -->
  <testcase classname="io.mosip.testrig.apirig.testscripts.OtpAuthNew" name="auth_EkycOtp_With_Valid_VID_Smoke_Pos" time="1.354">
    <failure type="io.mosip.testrig.apirig.admin.fw.util.AdminTestException" message="Internal Server Error. Hence marking the test case as failed">
      <![CDATA[io.mosip.testrig.apirig.admin.fw.util.AdminTestException: Internal Server Error. Hence marking the test case as failed
	at io.mosip.testrig.apirig.authentication.fw.util.OutputValidationUtil.doJsonOutputValidation(OutputValidationUtil.java:476)
	at io.mosip.testrig.apirig.authentication.fw.util.OutputValidationUtil.doJsonOutputValidation(OutputValidationUtil.java:468)
	at io.mosip.testrig.apirig.testscripts.OtpAuthNew.test(OtpAuthNew.java:222)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:196)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.main(MosipTestRunner.java:137)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- auth_EkycOtp_With_Valid_VID_Smoke_Pos -->
  <testcase classname="io.mosip.testrig.apirig.testscripts.OtpAuthNew" name="auth_EkycOtp_Auth_With_Invalid_Past_Timestamp_UIN_Neg" time="0.001">
    <skipped/>
  </testcase> <!-- auth_EkycOtp_Auth_With_Invalid_Past_Timestamp_UIN_Neg -->
  <testcase classname="io.mosip.testrig.apirig.testscripts.OtpAuthNew" name="auth_EkycOtp_With_Invalid_Past_Timestamp_VID_Neg" time="1.228">
    <failure type="io.mosip.testrig.apirig.admin.fw.util.AdminTestException" message="Internal Server Error. Hence marking the test case as failed">
      <![CDATA[io.mosip.testrig.apirig.admin.fw.util.AdminTestException: Internal Server Error. Hence marking the test case as failed
	at io.mosip.testrig.apirig.authentication.fw.util.OutputValidationUtil.doJsonOutputValidation(OutputValidationUtil.java:476)
	at io.mosip.testrig.apirig.authentication.fw.util.OutputValidationUtil.doJsonOutputValidation(OutputValidationUtil.java:468)
	at io.mosip.testrig.apirig.testscripts.OtpAuthNew.test(OtpAuthNew.java:222)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:196)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.main(MosipTestRunner.java:137)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- auth_EkycOtp_With_Invalid_Past_Timestamp_VID_Neg -->
  <testcase classname="io.mosip.testrig.apirig.testscripts.OtpAuthNew" name="auth_EkycOtp_Auth_With_Invalid_Future_Timestamp_UIN_Neg" time="0.001">
    <skipped/>
  </testcase> <!-- auth_EkycOtp_Auth_With_Invalid_Future_Timestamp_UIN_Neg -->
  <testcase classname="io.mosip.testrig.apirig.testscripts.OtpAuthNew" name="auth_EkycOtp_With_Invalid_Future_Timestamp_VID_Neg" time="1.311">
    <failure type="io.mosip.testrig.apirig.admin.fw.util.AdminTestException" message="Internal Server Error. Hence marking the test case as failed">
      <![CDATA[io.mosip.testrig.apirig.admin.fw.util.AdminTestException: Internal Server Error. Hence marking the test case as failed
	at io.mosip.testrig.apirig.authentication.fw.util.OutputValidationUtil.doJsonOutputValidation(OutputValidationUtil.java:476)
	at io.mosip.testrig.apirig.authentication.fw.util.OutputValidationUtil.doJsonOutputValidation(OutputValidationUtil.java:468)
	at io.mosip.testrig.apirig.testscripts.OtpAuthNew.test(OtpAuthNew.java:222)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:196)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.main(MosipTestRunner.java:137)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- auth_EkycOtp_With_Invalid_Future_Timestamp_VID_Neg -->
  <testcase classname="io.mosip.testrig.apirig.testscripts.OtpAuthNew" name="auth_EkycOtp_Auth_With_Invalid_Empty_Timestamp_UIN_Neg" time="0.002">
    <skipped/>
  </testcase> <!-- auth_EkycOtp_Auth_With_Invalid_Empty_Timestamp_UIN_Neg -->
  <testcase classname="io.mosip.testrig.apirig.testscripts.OtpAuthNew" name="auth_EkycOtp_With_Invalid_Empty_Timestamp_VID_Neg" time="0.002">
    <skipped/>
  </testcase> <!-- auth_EkycOtp_With_Invalid_Empty_Timestamp_VID_Neg -->
  <testcase classname="io.mosip.testrig.apirig.testscripts.OtpAuthNew" name="auth_EkycOtp_With_revoke_VID_Smoke_Pos" time="1.23">
    <failure type="io.mosip.testrig.apirig.admin.fw.util.AdminTestException" message="Internal Server Error. Hence marking the test case as failed">
      <![CDATA[io.mosip.testrig.apirig.admin.fw.util.AdminTestException: Internal Server Error. Hence marking the test case as failed
	at io.mosip.testrig.apirig.authentication.fw.util.OutputValidationUtil.doJsonOutputValidation(OutputValidationUtil.java:476)
	at io.mosip.testrig.apirig.authentication.fw.util.OutputValidationUtil.doJsonOutputValidation(OutputValidationUtil.java:468)
	at io.mosip.testrig.apirig.testscripts.OtpAuthNew.test(OtpAuthNew.java:222)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:196)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.main(MosipTestRunner.java:137)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- auth_EkycOtp_With_revoke_VID_Smoke_Pos -->
  <testcase classname="io.mosip.testrig.apirig.testscripts.OtpAuthNew" name="auth_EkycOtp_With_Invalid_individualId_uin_neg" time="1.167">
    <failure type="io.mosip.testrig.apirig.admin.fw.util.AdminTestException" message="Internal Server Error. Hence marking the test case as failed">
      <![CDATA[io.mosip.testrig.apirig.admin.fw.util.AdminTestException: Internal Server Error. Hence marking the test case as failed
	at io.mosip.testrig.apirig.authentication.fw.util.OutputValidationUtil.doJsonOutputValidation(OutputValidationUtil.java:476)
	at io.mosip.testrig.apirig.authentication.fw.util.OutputValidationUtil.doJsonOutputValidation(OutputValidationUtil.java:468)
	at io.mosip.testrig.apirig.testscripts.OtpAuthNew.test(OtpAuthNew.java:222)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:196)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.main(MosipTestRunner.java:137)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- auth_EkycOtp_With_Invalid_individualId_uin_neg -->
  <testcase classname="io.mosip.testrig.apirig.testscripts.OtpAuthNew" name="auth_EkycOtp_With_Invalid_individualId_VID_neg" time="1.343">
    <failure type="io.mosip.testrig.apirig.admin.fw.util.AdminTestException" message="Internal Server Error. Hence marking the test case as failed">
      <![CDATA[io.mosip.testrig.apirig.admin.fw.util.AdminTestException: Internal Server Error. Hence marking the test case as failed
	at io.mosip.testrig.apirig.authentication.fw.util.OutputValidationUtil.doJsonOutputValidation(OutputValidationUtil.java:476)
	at io.mosip.testrig.apirig.authentication.fw.util.OutputValidationUtil.doJsonOutputValidation(OutputValidationUtil.java:468)
	at io.mosip.testrig.apirig.testscripts.OtpAuthNew.test(OtpAuthNew.java:222)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:196)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.main(MosipTestRunner.java:137)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- auth_EkycOtp_With_Invalid_individualId_VID_neg -->
  <testcase classname="io.mosip.testrig.apirig.testscripts.OtpAuthNew" name="auth_EkycOtp_With_Blank_individualId_uin_neg" time="1.229">
    <failure type="io.mosip.testrig.apirig.admin.fw.util.AdminTestException" message="Internal Server Error. Hence marking the test case as failed">
      <![CDATA[io.mosip.testrig.apirig.admin.fw.util.AdminTestException: Internal Server Error. Hence marking the test case as failed
	at io.mosip.testrig.apirig.authentication.fw.util.OutputValidationUtil.doJsonOutputValidation(OutputValidationUtil.java:476)
	at io.mosip.testrig.apirig.authentication.fw.util.OutputValidationUtil.doJsonOutputValidation(OutputValidationUtil.java:468)
	at io.mosip.testrig.apirig.testscripts.OtpAuthNew.test(OtpAuthNew.java:222)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:196)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.main(MosipTestRunner.java:137)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- auth_EkycOtp_With_Blank_individualId_uin_neg -->
  <testcase classname="io.mosip.testrig.apirig.testscripts.OtpAuthNew" name="auth_EkycOtp_With_Blank_individualId_VID_neg" time="1.288">
    <failure type="io.mosip.testrig.apirig.admin.fw.util.AdminTestException" message="Internal Server Error. Hence marking the test case as failed">
      <![CDATA[io.mosip.testrig.apirig.admin.fw.util.AdminTestException: Internal Server Error. Hence marking the test case as failed
	at io.mosip.testrig.apirig.authentication.fw.util.OutputValidationUtil.doJsonOutputValidation(OutputValidationUtil.java:476)
	at io.mosip.testrig.apirig.authentication.fw.util.OutputValidationUtil.doJsonOutputValidation(OutputValidationUtil.java:468)
	at io.mosip.testrig.apirig.testscripts.OtpAuthNew.test(OtpAuthNew.java:222)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:196)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.main(MosipTestRunner.java:137)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- auth_EkycOtp_With_Blank_individualId_VID_neg -->
  <testcase classname="io.mosip.testrig.apirig.testscripts.OtpAuthNew" name="auth_EkycOtp_With_Missing_individualId_uin_neg" time="1.343">
    <failure type="io.mosip.testrig.apirig.admin.fw.util.AdminTestException" message="Internal Server Error. Hence marking the test case as failed">
      <![CDATA[io.mosip.testrig.apirig.admin.fw.util.AdminTestException: Internal Server Error. Hence marking the test case as failed
	at io.mosip.testrig.apirig.authentication.fw.util.OutputValidationUtil.doJsonOutputValidation(OutputValidationUtil.java:476)
	at io.mosip.testrig.apirig.authentication.fw.util.OutputValidationUtil.doJsonOutputValidation(OutputValidationUtil.java:468)
	at io.mosip.testrig.apirig.testscripts.OtpAuthNew.test(OtpAuthNew.java:222)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:196)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.main(MosipTestRunner.java:137)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- auth_EkycOtp_With_Missing_individualId_uin_neg -->
  <testcase classname="io.mosip.testrig.apirig.testscripts.OtpAuthNew" name="auth_EkycOtp_With_Missing_individualId_VID_neg" time="1.181">
    <failure type="io.mosip.testrig.apirig.admin.fw.util.AdminTestException" message="Internal Server Error. Hence marking the test case as failed">
      <![CDATA[io.mosip.testrig.apirig.admin.fw.util.AdminTestException: Internal Server Error. Hence marking the test case as failed
	at io.mosip.testrig.apirig.authentication.fw.util.OutputValidationUtil.doJsonOutputValidation(OutputValidationUtil.java:476)
	at io.mosip.testrig.apirig.authentication.fw.util.OutputValidationUtil.doJsonOutputValidation(OutputValidationUtil.java:468)
	at io.mosip.testrig.apirig.testscripts.OtpAuthNew.test(OtpAuthNew.java:222)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:196)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.main(MosipTestRunner.java:137)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- auth_EkycOtp_With_Missing_individualId_VID_neg -->
  <testcase classname="io.mosip.testrig.apirig.testscripts.OtpAuthNew" name="auth_EkycOtp_With_Invalid_transactionId_uin_Pos" time="0.001">
    <skipped/>
  </testcase> <!-- auth_EkycOtp_With_Invalid_transactionId_uin_Pos -->
  <testcase classname="io.mosip.testrig.apirig.testscripts.OtpAuthNew" name="auth_EkycOtp_With_Invalid_transactionId_VID_Neg" time="1.289">
    <failure type="io.mosip.testrig.apirig.admin.fw.util.AdminTestException" message="Internal Server Error. Hence marking the test case as failed">
      <![CDATA[io.mosip.testrig.apirig.admin.fw.util.AdminTestException: Internal Server Error. Hence marking the test case as failed
	at io.mosip.testrig.apirig.authentication.fw.util.OutputValidationUtil.doJsonOutputValidation(OutputValidationUtil.java:476)
	at io.mosip.testrig.apirig.authentication.fw.util.OutputValidationUtil.doJsonOutputValidation(OutputValidationUtil.java:468)
	at io.mosip.testrig.apirig.testscripts.OtpAuthNew.test(OtpAuthNew.java:222)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:196)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.main(MosipTestRunner.java:137)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- auth_EkycOtp_With_Invalid_transactionId_VID_Neg -->
  <testcase classname="io.mosip.testrig.apirig.testscripts.OtpAuthNew" name="auth_EkycOtp_With_Blank_transactionId_uin_Neg" time="0.0">
    <skipped/>
  </testcase> <!-- auth_EkycOtp_With_Blank_transactionId_uin_Neg -->
  <testcase classname="io.mosip.testrig.apirig.testscripts.OtpAuthNew" name="auth_EkycOtp_With_Blank_transactionId_VID_Neg" time="0.0">
    <skipped/>
  </testcase> <!-- auth_EkycOtp_With_Blank_transactionId_VID_Neg -->
  <testcase classname="io.mosip.testrig.apirig.testscripts.OtpAuthNew" name="auth_EkycOtp_With_Invalid_individualIdType_VID_Neg" time="0.01">
    <skipped/>
  </testcase> <!-- auth_EkycOtp_With_Invalid_individualIdType_VID_Neg -->
  <testcase classname="io.mosip.testrig.apirig.testscripts.OtpAuthNew" name="auth_EkycOtp_With_Blank_individualIdType_VID_Pos" time="0.0">
    <skipped/>
  </testcase> <!-- auth_EkycOtp_With_Blank_individualIdType_VID_Pos -->
  <testcase classname="io.mosip.testrig.apirig.testscripts.OtpAuthNew" name="auth_EkycOtp_With_Different_transaction_id_VID_Neg" time="1.359">
    <failure type="io.mosip.testrig.apirig.admin.fw.util.AdminTestException" message="Internal Server Error. Hence marking the test case as failed">
      <![CDATA[io.mosip.testrig.apirig.admin.fw.util.AdminTestException: Internal Server Error. Hence marking the test case as failed
	at io.mosip.testrig.apirig.authentication.fw.util.OutputValidationUtil.doJsonOutputValidation(OutputValidationUtil.java:476)
	at io.mosip.testrig.apirig.authentication.fw.util.OutputValidationUtil.doJsonOutputValidation(OutputValidationUtil.java:468)
	at io.mosip.testrig.apirig.testscripts.OtpAuthNew.test(OtpAuthNew.java:222)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:196)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.main(MosipTestRunner.java:137)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- auth_EkycOtp_With_Different_transaction_id_VID_Neg -->
  <testcase classname="io.mosip.testrig.apirig.testscripts.OtpAuthNew" name="auth_EkycOtp_With_Different_transaction_id_uin_Neg" time="1.211">
    <failure type="io.mosip.testrig.apirig.admin.fw.util.AdminTestException" message="Internal Server Error. Hence marking the test case as failed">
      <![CDATA[io.mosip.testrig.apirig.admin.fw.util.AdminTestException: Internal Server Error. Hence marking the test case as failed
	at io.mosip.testrig.apirig.authentication.fw.util.OutputValidationUtil.doJsonOutputValidation(OutputValidationUtil.java:476)
	at io.mosip.testrig.apirig.authentication.fw.util.OutputValidationUtil.doJsonOutputValidation(OutputValidationUtil.java:468)
	at io.mosip.testrig.apirig.testscripts.OtpAuthNew.test(OtpAuthNew.java:222)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:196)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.main(MosipTestRunner.java:137)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- auth_EkycOtp_With_Different_transaction_id_uin_Neg -->
  <testcase classname="io.mosip.testrig.apirig.testscripts.OtpAuthNew" name="auth_EkycOtp_With_invalid_uin_partner" time="1.076">
    <failure type="io.mosip.testrig.apirig.admin.fw.util.AdminTestException" message="Internal Server Error. Hence marking the test case as failed">
      <![CDATA[io.mosip.testrig.apirig.admin.fw.util.AdminTestException: Internal Server Error. Hence marking the test case as failed
	at io.mosip.testrig.apirig.authentication.fw.util.OutputValidationUtil.doJsonOutputValidation(OutputValidationUtil.java:476)
	at io.mosip.testrig.apirig.authentication.fw.util.OutputValidationUtil.doJsonOutputValidation(OutputValidationUtil.java:468)
	at io.mosip.testrig.apirig.testscripts.OtpAuthNew.test(OtpAuthNew.java:222)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:196)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.main(MosipTestRunner.java:137)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- auth_EkycOtp_With_invalid_uin_partner -->
</testsuite> <!-- EkycOtp -->
